### ISSUE TITLE
NIFs and Warhammer

### ISSUE THREAD

**Issue by MRejou** [philjord/jnif#1]
Hello !

First of all, thank you ! I'm working on a map editor for Warhammer Online and your project was of great help !

Now, I found two issues :
- a few NIFs files (maybe 5%) cannot be loaded,  resulting in a java heap space exception if I don't throw immediatly an exception when this kind of message is outputted :
  blocks[i].readFromStream for i=17 type= NiParticleSystem should have read off 156 but in fact read off 8186
- after each error, some static variables stay corrupted, and any new parse attemp result in errors. To "fix" that I had to invoke :
  NifPtr.allPtrs = new Vector<NifPtr>();
  NifRef.allRefs = new Vector<NifRef>();

If I can be of any help with your project I'd be glad to give any support I can :)

(please excuse for my "french" english)

**Comment by philjord** [comment]
Glad i could be of help!

I live in france now so french people have to put up with my terrible english.

I'm away for the week end now, but if you attach an example nif that's broken I'll fix it, and send you the steps i went through so you can move past issues in the future.

Im working mainly with bethesda games so I only test nif versions for their games.

It nice to hear of people working in java too!

Thanks,
Phil

----- Reply message -----

**Comment by MRejou** [comment]
Sure !

Collected few nifs you can get here : http://www.waronlinebuilder.org/perso/dev/nifprob/

I can add more if you want.

And thanks again, and it's not a hurry if we can't fix these files :)

**Comment by philjord** [comment]
Cool, they are all 20.3.0.9 version which is a recent version, beyond skyrim. I'll send an update and commit on sunday night hopefully, should be straight forward.

Thanks,
Phil

----- Reply message -----

**Comment by philjord** [comment]
MRejou,
I’ve made a commit to jnif.
0cea08f “Example 20.3.0.9 files now load without error”
If you pull the files should be loading now.

It turned out to be a strange issue. A long time ago I built-in support for game files from a game called “Black Prophecy” which had a version of 20.3.0.9.

But it turns out these files are a weird format that is not documented anywhere and certainly not 20.3.0.9

So I’ve gone through and moved all that code out to a special side system, so it no longer interferes with normal file loading.

Please pull and test against the rest of the files. Any issues just drop me a note and put the an example up and I should be able to turn it around more quickly.

It’s been really good to have some other file versions to test against.

It’s also interesting to see my early code (NifRef) is so old now that it has Vectors in it, not something you ever really see these days, I honestly thought you had made a typo when you said “new Vector()”.

Can I ask, are you using my jnifj3d code at all? If not how are you rendering the nif files(I know there’s lots of ways jogl, lwjgl, JME etc)?

Thanks,
Phil.

**Comment by MRejou** [comment]
Thanks a lot, pulling that this evening ! and I will give you some feedback in a long term testing.

About vector, yeah, I was surprised too ^^

About rendering I'm using javafx, as simple as java3d, works great, no particular performance issue and very good support for 2d UI stuff. If you have interrest in I'll give you the sources once it's stable, I can't publish it on GitHub because it may become a powerfull cheat tool (warhammer is a multiplayer game)
